name: Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install cc65
      run: sudo apt -y install cc65
    
    - name: Make
      run: make

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/main.nes
        asset_name: hello.nes
        tag: ${{ github.ref }}
        overwrite: true
