name: Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install cc65
      run: sudo apt -y install cc65
    
    - name: Make 
      run: make
